# Generated by Django 5.2.2 on 2025-06-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body_images',
            new_name='post_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro_images',
        ),
    ]
